local palette = require("zenburn.colors")
local color_ops = require("zenburn.color-ops")

local ts_bg = color_ops.LightenDarkenColor(palette.slateblue300, -10)
local prompt_bg = palette.slateblue300
local results_bg = palette.slateblue200

return {
	TelescopeBorder = { bg = ts_bg, fg = ts_bg },
	TelescopeMatching = { fg = "#a5bf82" },
	TelescopeMultiIcon = { fg = palette.teal900 },
	TelescopeMultiSelection = { fg = palette.skyblue300 },
	TelescopeNormal = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewBlock = { fg = palette.sunsetpurple },
	TelescopePreviewBorder = { bg = ts_bg, fg = ts_bg },
	TelescopePreviewCharDev = { fg = palette.sunsetpurple },
	TelescopePreviewDate = { fg = palette.teal900 },
	TelescopePreviewDirectory = { fg = palette.teal900 },
	TelescopePreviewExecute = { fg = palette.teal900 },
	TelescopePreviewGroup = { fg = palette.sunsetpurple },
	TelescopePreviewHyphen = { fg = "#242940" },
	TelescopePreviewLine = { bg = "#272c42" },
	TelescopePreviewLink = { fg = "#a5bf82" },
	TelescopePreviewMatch = { bg = "#e4aa80", fg = "#392313" },
	TelescopePreviewMessage = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewMessageFillchar = { bg = ts_bg, fg = "#2b3354" },
	TelescopePreviewNormal = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewPipe = { fg = palette.sunsetpurple },
	TelescopePreviewRead = { fg = palette.sunsetpurple },
	TelescopePreviewSize = { fg = palette.teal900 },
	TelescopePreviewSocket = { fg = palette.skyblue300 },
	TelescopePreviewSticky = { fg = palette.skyblue300 },
	TelescopePreviewTitle = { bg = "#a5bf82", fg = "#1e2132" },
	TelescopePreviewUser = { fg = palette.sunsetpurple },
	TelescopePreviewWrite = { fg = palette.skyblue300 },
	TelescopePromptBorder = { bg = prompt_bg, fg = prompt_bg },
	TelescopePromptCounter = { fg = "#cccccc" },
	TelescopePromptNormal = { bg = prompt_bg, fg = "#cccccc" },
	TelescopePromptPrefix = { fg = palette.skyblue300 },
	TelescopePromptTitle = { bg = palette.skyblue300, fg = prompt_bg },
	TelescopeResultsBorder = { bg = results_bg, fg = results_bg },
	TelescopeResultsClass = { fg = palette.skyblue300 },
	TelescopeResultsComment = { fg = "#6b7089" },
	TelescopeResultsConstant = { fg = palette.sunsetpurple },
	TelescopeResultsDiffAdd = { bg = "#45493e", fg = "#c4c7b5" },
	TelescopeResultsDiffChange = { bg = "#384851", fg = "#b7c5c8" },
	TelescopeResultsDiffDelete = { bg = "#53343b", fg = "#d2b2b2" },
	TelescopeResultsDiffUntracked = { fg = "#242940" },
	TelescopeResultsField = { fg = palette.skyblue300 },
	TelescopeResultsFunction = { fg = palette.skyblue300 },
	TelescopeResultsIdentifier = { fg = palette.teal900 },
	TelescopeResultsLineNr = { bg = "#1e2132", fg = "#444b71" },
	TelescopeResultsNormal = { bg = results_bg, fg = "#cccccc" },
	TelescopeResultsNumber = { fg = palette.sunsetpurple },
	TelescopeResultsOperator = { fg = palette.skyblue300 },
	TelescopeResultsSpecialComment = { fg = "#a5bf82" },
	TelescopeResultsTitle = { bg = results_bg, fg = results_bg },
	TelescopeResultsVariable = { fg = "#a5bf82" },
	TelescopeSelection = { bg = prompt_bg },
	TelescopeSelectionCaret = { bg = "#272c42" },
	TelescopeTitle = { bg = ts_bg, fg = "#cccccc" },
}
